##### Suponha que estejamos testando as moedas que serão utilizadas por árbitros de futebol nas competições da Copa do Mundo. Atualmente, estas moedas são personalizadas e utilizadas em certos momentos dos jogos para decidir, na sorte, uma disputa. Nosso objetivo é verificar se as moedas que serão utilizadas nas competições não sejam viciadas.

##### Para isso testes foram realizados com cinco moedas e os resultados foram os seguintes:

##### m1 = 'CCcCCccCCCccCcCccCcCcCCCcCCcccCCcCcCcCcccCCcCcccCc'
##### m2 = 'CCCCCccCccCcCCCCccCccccCccCccCCcCccCcCcCCcCccCccCc'
##### m3 = 'CccCCccCcCCCCCCCCCCcccCccCCCCCCccCCCcccCCCcCCcccCC'
##### m4 = 'cCCccCCccCCccCCccccCcCcCcCcCcCcCCCCccccCCCcCCcCCCC'
##### m5 = 'CCCcCcCcCcCCCcCCcCcCCccCcCCcccCccCCcCcCcCcCcccccCc'

##### Acima, temos o resultado de 50 lançamentos de cada moeda (m1, m2, m3, m4 e m5), onde c representa a ocorrência do evento CARA e C representa a ocorrência do evento COROA.

<img src="Extras\Cara_Coroa.png">

In [63]:
import pandas as pd

In [64]:
m1 = 'CCcCCccCCCccCcCccCcCcCCCcCCcccCCcCcCcCcccCCcCcccCc'
m2 = 'CCCCCccCccCcCCCCccCccccCccCccCCcCccCcCcCCcCccCccCc'
m3 = 'CccCCccCcCCCCCCCCCCcccCccCCCCCCccCCCcccCCCcCCcccCC'
m4 = 'cCCccCCccCCccCCccccCcCcCcCcCcCcCCCCccccCCCcCCcCCCC'
m5 = 'CCCcCcCcCcCCCcCCcCcCCccCcCCcccCccCCcCcCcCcCcccccCc'

In [65]:
#cria um dicionario com listas dos eventos
eventos = {'m1' : list(m1),
            'm2' : list(m2),
            'm3' : list(m3),
            'm4' : list(m4),
            'm5' : list(m5)}

In [66]:
#cria um DF com os eventos
dataset = pd.DataFrame(eventos)
dataset

   m1 m2 m3 m4 m5
0   C  C  C  c  C
1   C  C  c  C  C
2   c  C  c  C  C
3   C  C  C  c  c
4   C  C  C  c  C
5   c  c  c  C  c
6   c  c  c  C  C
7   C  C  C  c  c
8   C  c  c  c  C
9   C  c  C  C  c
10  c  C  C  C  C
11  c  c  C  c  C
12  C  C  C  c  C
13  c  C  C  C  c
14  C  C  C  C  C
15  c  C  C  c  C
16  c  c  C  c  c
17  C  c  C  c  C
18  c  C  C  c  c
19  C  c  c  C  C
20  c  c  c  c  C
21  C  c  c  C  c
22  C  c  C  c  c
23  C  C  c  C  C
24  c  c  c  c  c
25  C  c  C  C  C
26  C  C  C  c  C
27  c  c  C  C  c
28  c  c  C  c  c
29  c  C  C  C  c
30  C  C  C  c  C
31  C  c  c  C  c
32  c  C  c  C  c
33  C  c  C  C  C
34  c  c  C  C  C
35  C  C  C  c  c
36  c  c  c  c  C
37  C  C  c  c  c
38  c  c  c  c  C
39  c  C  C  C  c
40  c  C  C  C  C
41  C  c  C  C  c
42  C  C  c  c  C
43  c  c  C  C  c
44  C  c  C  C  c
45  c  C  c  c  c
46  c  c  c  C  c
47  c  c  c  C  c
48  C  C  C  C  C
49  c  c  C  C  c

In [67]:
#cria um DF com indice e coluna e um dado auxiliar
df = pd.DataFrame(  data= ['Cara', 'Coroa'],
                    index = ['c', 'C'], 
                    columns = ['Faces'])
df

   Faces
c   Cara
C  Coroa

In [68]:
# Concatena objetos pandas ao longo de um eixo específico 
# axis = 1 pq é uma coluna
for item in dataset:
    df = pd.concat([df,dataset[item].value_counts()], axis=1)
df

   Faces  m1  m2  m3  m4  m5
c   Cara  25  26  19  23  25
C  Coroa  25  24  31  27  25

In [76]:
#sm1 = pd.Series(list(m3))
#sm1.value_counts()

C    31
c    19
dtype: int64